services:
  - type: web
    name: event-booking-backend
    runtime: docker
    plan: free
    buildCommand: cd backend && ./mvnw clean package -DskipTests
    startCommand: cd backend && java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17